collections:
    chapters:
      output: true
      sort_by: chap_num

defaults:
    - scope:
        path: ""
        type: "authors"
      values:
        layout: "author"
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - _compress_images_cache.yml

# https://github.com/valerijaspasojevic/jekyll-compress-images