# config.yml

backend:
   name: git-gateway
   branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
   - name: 'blog'
     label: 'Posts'
     folder: '_posts/'
     create: true
     slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
     editor:
       preview: false
     fields:
       - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
       - { label: 'Title', name: 'title', widget: 'string' }
       - { label: 'Title Glyph', name: 'glyph', widget: 'file', required: false}
       - { label: 'Title Glyph Alt Text', name: 'glyph_altText', widget: 'string', required: false }
       - { label: 'Entry No.', name: 'entry_number', widget: 'number', valueType: int, min: 0, max: 109, step: 1 }
       - { label: 'Location', name: 'location', widget: 'string', required: false }
       - { label: 'Publish Date', name: 'date', widget: 'datetime', required: false }
       - { label: 'Entry length', name: 'length_layout', widget: 'select', required: false, options: ['X-Small', 'Small', 'Medium', 'Large', 'X-Large' ]}
       - { label: 'Component Type', name: 'component_type', widget: 'select', required: true, options: ['xs_1', 'xs_2-1', 'xs_2-2', 'xs_2-3', 'xs_3', 's_1', 's_2', 's_3', 's_4', 's_5', 'm_1', 'm_2', 'm_3', 'l_1', 'l_2', 'xl_1', 'xl_a', 'quote_1', 'quote_2', 'quote_3', 'quote_4', 'lyrics', 'p_1', 'p_2', 'p_3'] }
       - { label: 'Custom CSS', name: 'custom_css', widget: 'select', multiple: true, required: false, options: ['Reflect', 'BigSpace', 'BigTime', 'AlignEntryCenter', 'ImgAfter', 'ExtraLong', 'Rotate180', 'Scatter', 'Quote', 'Q1', 'Q2', 'Q3', 'Q4']}
       - { label: 'Custom Background Color', name: 'custom_bg', widget: 'select', required: false, options: ['gladeGreen','pampas','greenWhite', 'greenSmoke', 'flaxSmoke','whiteRock','dustStorm','mutedPink','sepia','heavyMetal','holly','gunMetal','kangaroo','eagle', 'white', 'gray', 'black']}
       - { label: 'Interaction', name: 'interaction', widget: 'select', multiple: true, required: false, options: ['draggable']}
       - { label: 'Image CSS', name: 'image_css', widget: 'select', multiple: true, required: false, options: ['draggable']}
       - { label: 'Image 1', name: 'file', widget: 'file', required: false }
       - { label: 'Image 2', name: 'file_2', widget: 'file', required: false }
       - { label: 'Image 3', name: 'file_3', widget: 'file', required: false }
       - { label: 'Image 4', name: 'file_4', widget: 'file', required: false }
       - { label: 'Image 5', name: 'file_5', widget: 'file', required: false }
       - { label: 'Image 6', name: 'file_6', widget: 'file', required: false }
       - { label: 'Image 7', name: 'file_7', widget: 'file', required: false }
       - { label: 'Image 8', name: 'file_8', widget: 'file', required: false }
       - { label: 'Image 9', name: 'file_9', widget: 'file', required: false }
       - { label: 'Image 10', name: 'file_10', widget: 'file', required: false }
       - { label: 'Body', name: 'body', widget: 'markdown' }

   - name: 'Chapters'
     label: 'Chapters'
     editor:
       preview: false
     create: true
     files:
       - label: 'Chapitre Un'
         name: 'chapitre_un'
         file: 'chapters/chapitre_un.html'
         fields:
           - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
           - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
           - { label: 'Body', name: 'body', widget: 'markdown' }
           - { label: 'chap_num', name: 'chap_num'}
           - { label: 'subtitle', name: 'subtitle'}
           - { label: 'Image', name: 'image', widget: 'file', allow_multiple: true, required: false }
           - { label: 'SVG', name: 'SVG', widget: 'file', allow_multiple: true, required: false }
       - label: 'Chapitre Deux'
         name: 'chapitre_deux'
         file: 'chapters/chapitre_deux.html'
         fields:
           - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
           - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
           - { label: 'Body', name: 'body', widget: 'markdown' }
           - { label: 'chap_num', name: 'chap_num'}
           - { label: 'subtitle', name: 'subtitle'}
           - { label: 'Image', name: 'image', widget: 'file', allow_multiple: true, required: false }
           - { label: 'SVG', name: 'SVG', widget: 'file', allow_multiple: true, required: false }
       - label: 'Chapitre Trois'
         name: 'chapitre_trois'
         file: 'chapters/chapitre_trois.html'
         fields:
           - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
           - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
           - { label: 'Body', name: 'body', widget: 'markdown' }
           - { label: 'chap_num', name: 'chap_num'}
           - { label: 'subtitle', name: 'subtitle'}
           - { label: 'Image', name: 'image', widget: 'file', allow_multiple: true, required: false }
           - { label: 'SVG', name: 'SVG', widget: 'file', allow_multiple: true, required: false }
       - label: 'Chapitre Quatre'
         name: 'chapitre_quatre'
         file: 'chapters/chapitre_quatre.html'
         fields:
           - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
           - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
           - { label: 'Body', name: 'body', widget: 'markdown' }
           - { label: 'chap_num', name: 'chap_num'}
           - { label: 'subtitle', name: 'subtitle'}
           - { label: 'Image', name: 'image', widget: 'file', allow_multiple: true, required: false }
           - { label: 'SVG', name: 'SVG', widget: 'file', allow_multiple: true, required: false }
       - label: 'Chapitre Cinq'
         name: 'chapitre_cinq'
         file: 'chapters/chapitre_cinq.html'
         fields:
           - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
           - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
           - { label: 'Body', name: 'body', widget: 'markdown' }
           - { label: 'chap_num', name: 'chap_num'}
           - { label: 'subtitle', name: 'subtitle'}
           - { label: 'Image', name: 'image', widget: 'file', allow_multiple: true, required: false }
           - { label: 'SVG', name: 'SVG', widget: 'file', allow_multiple: true, required: false }
       - label: 'Chapitre Six'
         name: 'chapitre_six'
         file: 'chapters/chapitre_six.html'
         fields:
           - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
           - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
           - { label: 'Body', name: 'body', widget: 'markdown' }
           - { label: 'chap_num', name: 'chap_num'}
           - { label: 'subtitle', name: 'subtitle'}
           - { label: 'Image', name: 'image', widget: 'file', allow_multiple: true, required: false }
           - { label: 'SVG', name: 'SVG', widget: 'file', allow_multiple: true, required: false }
       - label: 'Chapitre Sept'
         name: 'chapitre_sept'
         file: 'chapters/chapitre_sept.html'
         fields:
           - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
           - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
           - { label: 'Body', name: 'body', widget: 'markdown' }
           - { label: 'chap_num', name: 'chap_num'}
           - { label: 'subtitle', name: 'subtitle'}
           - { label: 'Image', name: 'image', widget: 'file', allow_multiple: true, required: false }
           - { label: 'SVG', name: 'SVG', widget: 'file', allow_multiple: true, required: false }

    
   - name: 'config'
     label: 'Navigation config'
     editor:
       preview: false
     files:
       - label: 'Navigation'
         name: 'navigation'
         file: '_data/navigation.yml'
         fields:
           - label: 'Navigation Items'
             name: 'items'
             widget: 'list'
             fields:
               - {label: 'Name', name: 'name', widget: 'string'}
               - {label: 'Link', name: 'link', widget: 'string'}