# config.yml

backend:
   name: git-gateway
   branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
   - name: 'blog'
     label: 'Posts'
     folder: '_posts/'
     create: true
     slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
     editor:
       preview: false
     fields:
       - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
       - { label: 'Title', name: 'title', widget: 'string' }
       - { label: 'Entry No.', name: 'entry_number', widget: 'number', valueType: int, min: 0, max: 109, step: 1 }
       - { label: 'Location', name: 'location', widget: 'string', required: false }
       - { label: 'Publish Date', name: 'date', widget: 'datetime', required: false }
       - { label: 'Entry length', name: 'length_layout', widget: 'select', required: false, options: ['X-Small', 'Small', 'Medium', 'Large', 'X-Large' ]}
       - { label: 'Custom CSS', name: 'custom_css', widget: 'select', multiple: true, required: false, options: ['Reflect', 'BigSpace', 'BigTime', 'AlignEntryCenter', 'ImgAfter', 'Rotate180', 'Scatter']}
       - { label: 'Interaction', name: 'interaction', widget: 'select', multiple: true, required: false, options: ['draggable']}
       - { label: 'Image CSS', name: 'image_css', widget: 'select', multiple: true, required: false, options: ['draggable']}
       - label: 'Media'
         name: 'file'
         widget: 'file'
         multiple: true
         required: false
         media_library: 
           config:
             multiple: true 
       - { label: 'Body', name: 'body', widget: 'markdown' }

   - name: 'pages'
     label: 'Pages'
     editor:
       preview: false
     files:
       - label: 'About Page'
         name: 'about'
         file: 'about.md'
         fields:
           - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
           - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
           - { label: 'Body', name: 'body', widget: 'markdown' }
    
   - name: 'config'
     label: 'Config'
     editor:
       preview: false
     files:
       - label: 'Navigation'
         name: 'navigation'
         file: '_data/navigation.yml'
         fields:
           - label: 'Navigation Items'
             name: 'items'
             widget: 'list'
             fields:
               - {label: 'Name', name: 'name', widget: 'string'}
               - {label: 'Link', name: 'link', widget: 'string'}

   - name: 'Chapter_splash'
     label: 'Chapter_splash'
     folder: '_chapter_splash/'
     create: true
     editor:
       preview: false
     fields:
       - { label: 'Title', name: 'title'}
       - label: 'Media'
         name: 'file'
         widget: 'file'
         multiple: true
         required: false
         media_library:
           config:
             multiple: true